name: coin_market
description: "Coin Market - Track cryptocurrency prices and market data in real-time."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2



  

dependencies:
  cupertino_icons: ^1.0.8
  adaptive_theme: ^3.7.0
  dartx: ^1.2.0
  dio: ^5.7.0
  drop_down_list: ^2.0.0
  dropdown_button2: ^2.3.9
  envied: ^0.5.4+1
  extended_image: ^9.1.0
  firebase_performance_dio: ^0.7.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_confetti: ^0.4.0
  flutter_hooks: ^0.21.2
  flutter_i18n: ^0.36.2
  flutter_screenutil: ^5.9.3
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  form_validator: ^2.1.1
  freezed_annotation: ^2.4.4
  get_it: ^8.0.0
  json_annotation: ^4.9.0
  go_router: ^14.2.8
  go_router_paths: ^0.2.2
 
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_serializable: ^6.8.0
  load_switch: ^2.1.0
  loader_overlay: ^4.0.3
  local_auth: ^2.3.0
  modal_bottom_sheet: ^3.0.0
  path_provider: ^2.1.4
  pinput: ^5.0.1
  provider: ^6.1.2
  dio_smart_retry: ^6.0.0
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  smooth_page_indicator: ^1.2.0+3
  spider: ^4.2.2
  timeago: ^3.7.0
  toastification: ^2.3.0
  url_launcher: ^6.3.0
  webview_flutter: ^4.11.0
  another_flushbar: ^1.12.30
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.3.0
  hooks_riverpod: ^2.6.1
  google_maps_places_autocomplete_widgets: ^1.3.3
  google_places_autocomplete_text_field: ^1.1.0
  web_socket_channel: ^2.4.0
  freezed: ^2.5.7


dev_dependencies:
  build_runner: ^2.4.13
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/env/

# fonts:
#   - family: Poppins
#     fonts:
#       - asset: assets/fonts/Poppins-Black.ttf
#       - asset: assets/fonts/Poppins-BlackItalic.ttf
#         style: italic
#       - asset: assets/fonts/Poppins-Bold.ttf
#         weight: 700
#       - asset: assets/fonts/Poppins-BoldItalic.ttf
#         weight: 700
#         style: italic
#       - asset: assets/fonts/Poppins-ExtraBold.ttf
#         weight: 800
#       - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
#         weight: 800
#         style: italic
#       - asset: assets/fonts/Poppins-Medium.ttf
#         weight: 500
#       - asset: assets/fonts/Poppins-MediumItalic.ttf
#         weight: 500
#         style: italic
#       - asset: assets/fonts/Poppins-Regular.ttf
#         weight: 400
#       - asset: assets/fonts/Poppins-Italic.ttf
#         weight: 400
#         style: italic
#       - asset: assets/fonts/Poppins-Light.ttf
#         weight: 300
#       - asset: assets/fonts/Poppins-LightItalic.ttf
#         weight: 300
#         style: italic
#       - asset: assets/fonts/Poppins-ExtraLight.ttf
#         weight: 200
#       - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
#         weight: 200
#         style: italic
#       - asset: assets/fonts/Poppins-Thin.ttf
#         weight: 100
#       - asset: assets/fonts/Poppins-ThinItalic.ttf
#         weight: 100
#         style: italic

